### ISSUE TITLE
error LNK1104: cannot open file 'libmingwex.a'

### ISSUE THREAD

**Issue by riverstore** [BrunoReX/build-scripts#1]
Hi,

First, I'd like to thanks for the great tutorial. I follow your L-SMASH building tutorial, everything fine until I build AviSynth plugin, I get error message

Error   1   error LNK1104: cannot open file 'libmingwex.a'  g:\code\cpp\lsmash\L-SMASH-Works\AviSynth\LINK  LSMASHSource

Here is my config

http://i.imgur.com/hQIiP0s.png

Please help me. Thanks a lot.

**Comment by BrunoReX** [comment]
It should be `g:\msys64\mingw32\i686-w64-mingw32\lib`
Not `g:\msys64\i686-w64-mingw32\lib`

And also: `g:\msys64\mingw32\local-msvc\lib` not `g:\msys64\local-msvc\lib`

**Comment by riverstore** [comment]
Thanks a lot. Building successfull now. Hope to see more tuts from you ^^
